In [88]:
import pickle
import pandas as pd
from sklearn.preprocessing import binarize
import numpy as np
from sklearn.metrics import confusion_matrix
import json

In [20]:
stimuli_dataset = "processed_paired_stimuli/4_10.csv"

stimuli_data = pd.read_csv(stimuli_dataset,sep=",",index_col=0)
stimuli_1 , stimuli_2 = stimuli_data['slideNumber'].unique()
        
X = stimuli_data.iloc[:, :-2]
Y = stimuli_data.iloc[:, -1:]
Y = pd.DataFrame(binarize(Y, threshold=stimuli_1, copy=True))


In [30]:
Y.apply(pd.value_counts)

0
0.0  1349
1.0   856

In [48]:
from keras.models import load_model
model = load_model('model.h5')

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
classes = model.predict_classes(X, batch_size=10)
probability = model.predict(X,batch_size=10)

In [51]:
if there are more 1's than 0's 

In [52]:
with open('svm_model.pkl', 'rb') as f:
    svm = pickle.load(f)
svm_preds = svm.predict(X)
svm_preds

In [59]:
svm_preds = svm.predict(X)
svm_preds

array([0., 0., 0., ..., 0., 0., 0.])

In [57]:
confusion_matrix(Y, svm_preds)

array([[1349,    0],
       [ 517,  339]])

In [64]:
ii = np.where(classes == 1)[0]
ii

array([ 202,  203,  204,  205,  206,  207,  208,  209,  210,  211,  218,
        219,  220,  221,  222,  223,  229,  230,  231,  232,  240,  241,
        242,  300,  301,  628,  638,  639,  640,  641,  642,  643,  644,
        645,  646,  647,  648,  704,  705,  706,  731,  732,  733,  734,
        735,  736,  737,  738,  739,  740,  741,  742,  743,  744,  745,
        746,  747,  748,  752,  753,  754,  755,  789,  790,  791,  794,
        795,  796,  909,  910,  911,  963,  964,  965, 1024, 1025, 1026,
       1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037,
       1038, 1039, 1040, 1041, 1044, 1045, 1046, 1047, 1276, 1277, 1278,
       1279, 1280, 1281, 1282, 1283, 1410, 1411, 1412, 1413, 1414, 1415,
       1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426,
       1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437,
       1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448,
       1449, 1451, 1452, 1453, 1481, 1482, 1483, 14

In [80]:
right = np.count_nonzero(classes == 1)
left = np.count_nonzero(classes == 0)

In [81]:
left ,right

(1698, 507)

In [84]:
length = len(X)

In [85]:
length = len(X)
accuracy_left = left / length
accuracy_right = right/length 

accuracy_left , accuracy_right

In [86]:
accuracy_left , accuracy_right

(0.7700680272108843, 0.22993197278911565)

In [91]:
if accuracy_left > accuracy_right:
    with open('direction.json' , 'w') as g:
        json.dump('L' , g)
else:
        json.dump('R' , g)
        